import { BOMBS } from './catalogue.js';
import { WEAPONS } from './weapons.js';

// Player-facing instructions grouped by task; weapon descriptions share the catalogue.
export const PLAY_GUIDE = [
  { id: 'start', title: 'Quick start',
    summary: 'This is your shared Free Play world. Buildings, craters and saved vehicles stay when you leave. Ordinary Moorstead is a separate world.',
    steps: ['Enter with your own name and Free-play code. Each player uses their own login.',
      'To build: open Build, choose a block or ready-made build, aim at the ground and press Place.',
      'To drive: open Vehicles, place a starter, use its Vehicle control block, then Convert and Enter.',
      'To battle: open Menu → Battlefield / armies. Choose opposite teams, prepare your bases, then both press Place flag & ready.',
      'Reopen Guide at the top of the screen whenever you need it. Choose a topic for the full instructions.'],
    facts: ['Materials and ammunition are unlimited. There is no money or resource-gathering requirement in Free Play.',
      'You have unlimited health while exploring. Joining an army switches on battle health, shields and knockouts.',
      'Changes belong to both of you. Undo removes the latest shared change, even if the other player made it.'],
    tip: 'First battle goal: recruit a squad, ready both flags, then send the squad to Attack. A soldier entering the enemy flag zone can win.' },
  { id: 'controls', title: 'Move, aim and find each other',
    summary: 'The crosshair in the middle of the screen shows where you are aiming. Aim before placing, breaking or firing.',
    steps: ['Computer: WASD walks. Drag to look, or click the world to capture the mouse. Escape releases the mouse; Back to play closes a panel.',
      'Tablet: hold the movement arrows and drag across the world to look. Use Place, Break and Fire on the right.',
      'Space or Up / jump jumps. Outside battle, Fly or F toggles flight; Space / Up rises and Shift / Down descends. Z moves faster.',
      'Open Map to locate each other. Menu → Back to village returns you while outside an active battle.'],
    facts: ['Shortcuts: B = Build, X = Bombs, G = Weapons, M = Map, R = rotate a build, E = use a vehicle control, V = change vehicle camera.',
      'With the mouse captured, left click breaks an ordinary block, places a selected build, or fires the selected weapon. Right click uses the selected item. The labelled screen buttons work too.',
      'In battle you walk on the ground inside the gold battlefield boundary. Flight and ordinary vehicles are unavailable until you leave the army.'],
    tip: 'If the mouse feels stuck, press Escape. On a tablet, lift your finger to stop moving or firing.' },
  { id: 'building', title: 'Build, dig and undo',
    summary: 'Build one block at a time, use a larger brush, or place a complete structure.',
    steps: ['Open Build. Choose One block or a brush, set Brush size if offered, then choose a material. Search by block name.',
      'For a complete structure, choose a Ready-made build instead. Aim its preview where you want it.',
      'Press Rotate or R to turn a build, then Place. Keep the whole preview inside loaded ground.',
      'Aim at a block and use Break to remove it. Trenches and excavation brushes make larger defensive spaces.',
      'Use Undo to reverse the newest shared action. One Undo reverses a whole brush or prefab placement.'],
    facts: ['No supplies are consumed. Keep building without gathering resources.',
      'Walls and hills block shots. Leave doorways, wide routes and steps so soldiers can move.',
      'Shared history is limited. Undo is for recent actions, not a complete backup of every build.',
      'Battle wall damage can also appear in shared history. Ask each other before undoing.'],
    tip: 'A high flag is still capturable from below. Build defences around its ground zone instead of relying on height.' },
  { id: 'vehicles', title: 'Build and drive vehicles',
    summary: 'Convert a build into one movable object. Both players can use saved vehicles, one driver at a time.',
    steps: ['Open Vehicles and choose a starter car, plane, tank body or submarine. Aim at clear ground and press Place starter.',
      'Aim at its Vehicle control block and press Use core (E on a computer). Your connected placed blocks are highlighted.',
      'Review the selection. Choose Car, Plane or Submarine movement, then Convert. Press Enter to drive.',
      'W/S or forward/back arrows move; A/D or left/right arrows steer. Plane or submarine: Space / Up rises; Shift / Down descends.',
      'Use Change view or V for another camera. Park to get out. To rebuild it, open Vehicles and choose Edit build.'],
    facts: ['For your own design, add exactly one Vehicle control block. Only placed blocks are included; the natural ground stays behind.',
      'Limit: 512 blocks inside a 16 × 12 × 16 box, and 16 saved vehicles. Use manual corner selection if detection selects the wrong blocks.',
      'Park before joining an army. A starter tank body is a drivable build with a decorative gun. The firing army tank is placed from Army and follows orders; you do not drive it.'],
    tip: 'If Convert refuses, check for extra control blocks, an oversized build, or blocks touching a neighbouring structure.' },
  { id: 'battle', title: 'Start a battle',
    summary: 'Blue fights Red. Prepare first; fighting starts only when both teams are ready.',
    steps: ['Park any vehicle. Open Menu → Battlefield / armies and choose Join Blue army or Join Red army. Your opponent chooses the other colour.',
      'Stay inside the gold boundary. Build a base with cover and a route out. You can recruit troops while preparing.',
      'Stand on clear, supported ground in your base and press Place flag & ready. The flags must be at least 32 blocks apart.',
      'Wait for the other team to ready their flag. To change yours before the round starts, use Move flag here, then ready again.',
      'Once combat starts, use Army to command troops and deploy equipment. Move yourself or a soldier into the enemy flag zone to win.'],
    facts: ['Flags are locked in place during a round. Setup is for choosing bases; weapons unlock when both teams are ready.',
      'Army → Return to home base brings you back to your flag. It recharges in 10 seconds and does not heal you.',
      'After a win, Play another round resets armies, flags and scores but keeps terrain and fortifications.',
      'To leave an active battle, choose Army → Forfeit battle and confirm. The other army wins; your buildings stay.'],
    tip: 'Menus do not pause the match. A disconnected player pauses an active battle for up to 60 seconds. Reconnect in time to keep the round; otherwise the absent player forfeits.' },
  { id: 'squads', title: 'Recruit and command squads',
    summary: 'Recruit in batches, then send different groups to different jobs.',
    steps: ['Open Army → Recruit 10 soldiers. Recruitment refreshes after 25 seconds. Each team can have 30 soldiers, including those waiting to respawn.',
      'The first batch is Squad 1, then Squad 2, then Squad 3. New soldiers start on Attack and advance once the battle starts.',
      'Choose Command group: Squad 1, Squad 2, Squad 3 or All squads. This selects which of your units receive the next order.',
      'Choose Attack the enemy, Defend our flag, Follow me or Hold this position. To send a group somewhere else, aim at the ground first, then choose Move squad to aimed point.'],
    facts: ['Attack: infantry advance toward the enemy flag and fire as they go. Defend: guard your base. Follow: stay near you. Hold: move to the chosen position and stay there.',
      'Changing Command group alone does not issue an order. Choose the group, then press an order button.',
      'Health bars show how hurt soldiers are. Knocked-out soldiers return together in waves after 8–33 seconds, rather than instantly.',
      'Army tanks in the selected group follow orders too. Turrets stay put. All squads still controls only your own units.'],
    tip: 'Try Squad 1 on Defend and Squad 2 on Attack. Add Squad 3 when recruitment refreshes instead of sending every soldier away from your flag.' },
  { id: 'capture', title: 'Capture flags and breach walls',
    summary: 'Enter the enemy highlighted zone to win. There is no flag pickup or return trip.',
    steps: ['Find the enemy flag and its coloured capture zone. The zone extends three blocks out from the flag on the ground.',
      'Send soldiers using Army → Command group → Attack the enemy, or approach on foot yourself.',
      'A living, grounded player or soldier entering the zone immediately wins. Defenders in the zone do not cancel capture.',
      'If walls block the approach, attacking soldiers gradually shoot openings and advance through them. Keep your own routes wide enough for troops.'],
    facts: ['Capture uses horizontal distance. A flag on a tower can be captured from the ground below it.',
      'Turrets and tanks cannot capture flags. Use infantry or your player.',
      'A blocking wall block takes four breach hits, at most one hit per second. Several layers take longer; intact cover still stops shots.',
      'Breach holes change the shared terrain and remain after the battle. You can rebuild them.'],
    tip: 'Watch the flag zone, not just the kill score. One soldier getting through can win even against a larger army.' },
  { id: 'equipment', title: 'Turrets and firing tanks',
    summary: 'Turrets provide light automatic defence. Army tanks are slower, stronger units that move and fire for you.',
    steps: ['Join an army, then aim at visible, clear, level ground within 18 blocks. Leave a three-by-three space and room between equipment.',
      'Open Army and choose Squad 1, 2 or 3 in Command group. Equipment placed with All squads selected joins Squad 1.',
      'Press Place turret at aimed point or Place tank at aimed point. Wait 20 seconds before placing another piece of equipment.',
      'Turrets fire automatically at visible enemies during combat. Select a tank’s squad and give Attack, Defend, Follow or Hold orders.'],
    facts: ['Each team can field three turrets and two tanks. No resources are required; team limits and refresh timers control placement.',
      'Turret: 75 health, 28-block range, 6 damage every 2 seconds. Tank: 100 health, 38-block range, 28 damage every 3.5 seconds, before shields absorb damage.',
      'Equipment needs line of sight to shoot. Tanks engage enemies while infantry push toward the flag.',
      'Destroyed equipment does not return with soldier waves. Place a replacement when the cooldown and team limit allow it.'],
    tip: 'Place a turret where it can see an approach. A gun completely enclosed by walls cannot defend through them.' },
  { id: 'combat', title: 'Weapons, shields and bombs',
    summary: 'Select a weapon, aim and press Fire. Hold Fire for the machine gun. Supplies never run out.',
    steps: ['Open Weapons (G) or Bombs (X), then choose an item. Aim and use Fire or Throw / place.',
      'Computer: capture the mouse and use left click. Tablet: use the Fire button; hold it for the machine gun.',
      'Use cover and your Shield button. A shield dome protects nearby teammates for 12 seconds, with a 25-second cooldown.'],
    facts: ['Blue shield bars absorb damage before green health bars. A knocked-out player respawns after 5 seconds; soldiers wait for their wave.',
      'Your personal shield starts refilling after 3 seconds without a hit, at 10 points per second. This is separate from the shield dome you place for your team.',
      'In battle, your machine gun and plasma hit troops but do not dig terrain. Use explosives or attacking infantry to open walls. Explosions can also hurt units. Cover blocks shots; friendly fire does not damage your team.',
      'Mega and atom bombs are banned in an occupied battlefield. Gravity and sheep effects do not inflict battle damage.',
      ...WEAPONS.map(row => `${row.name} (outside battle): ${row.description}`),
      ...BOMBS.map(row => `${row.name}: ${row.description}`)],
    tip: 'Outside battle, explosions can still destroy shared buildings even though you have unlimited health. Use Undo promptly if you hit the wrong place.' },
  { id: 'reset', title: 'Save, reset and recover',
    summary: 'Accepted world changes save automatically. Full reset is a joint decision, not the usual way to restart a battle.',
    steps: ['For a recent mistake, use Undo. For another battle without losing buildings, finish or forfeit, then use Army → Play another round.',
      'For a fresh world, both players must be online. Each opens Full reset and presses Approve full reset within 30 seconds.',
      'The first approval shows Reset · 1/2. Nothing clears until the other player approves. One player pressing twice does not count.',
      'To recover, open Menu → Restore before last reset. Both players must approve restoration within 30 seconds. Finish any active battle first to access that menu option.'],
    facts: ['Full reset clears buildings, craters, vehicles and armies for both players, and returns you to the village. Your logins stay.',
      'The pre-reset world is a recovery checkpoint. Restoration swaps the current world and checkpoint; it is not an unlimited archive.',
      'Approvals expire after 30 seconds. Disconnects or changes to connected accounts cancel them. Reset and restoration approvals cannot be mixed.',
      'Exactly two accounts must be connected to approve. Both can agree to a Full reset during a battle.'],
    tip: 'If only one of you wants to stop playing, sign out or leave the battle. Do not reset the whole world.' },
  { id: 'trouble', title: 'If something is not working',
    summary: 'Read the message on screen first. Most refusals concern a cooldown, placement rule or connection.',
    steps: ['Cannot fire? Both teams must be ready. Wait if combat is paused, you are knocked out, or the weapon is cooling down.',
      'Soldiers will not move? Check Command group and the order. Attack squads need time to breach walls. Follow does not send them to the enemy flag.',
      'Cannot place equipment? Move closer, aim at loaded ground, clear a level three-by-three patch, and check the 20-second timer and team limits.',
      'Waiting for the world? Let it finish connecting. Use Menu → Reconnect if it stays stuck; refresh after a game update.',
      'Running slowly? In Menu choose Plain graphics. Gentle flashes, Gentle effects and Mute sound are available too.'],
    facts: ['If your opponent disconnects during combat, the battle pauses for up to 60 seconds. They should reconnect with the same account.',
      'A second tab using your login replaces your first connection. Use one account per player and one active tab each.',
      'For reset trouble, both must approve the same action within 30 seconds. A stale approval may require a fresh attempt.'],
    tip: 'Close with Back to play. Reopen from Guide, Menu → How to play, or Battle guide in Army.' }
];
